[package]
name = "day2_2022"
version = "0.1.0"
authors = ["D030971"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
